In [1]:
import pandas as pd

In [2]:
ox = pd.read_csv('C:\\Users\\sarah\\Documents\\IRONHACK\\Final_Project_Mod2\\data\\oxford_clean.csv')

In [3]:
ox

,Unnamed: 0,CountryName,RegionName,Date,C1_School closing,C2_Workplace closing,C3_Cancel public events,C4_Restrictions on gatherings,C5_Close public transport,C6_Stay at home requirements,...,H3_Contact tracing,H4_Emergency investment in healthcare,H5_Investment in vaccines,ConfirmedCases,ConfirmedDeaths,StringencyIndexForDisplay,StringencyLegacyIndexForDisplay,GovernmentResponseIndexForDisplay,ContainmentHealthIndexForDisplay,EconomicSupportIndexForDisplay
0,0,Aruba,NaN,20200101,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.00,0.0,0.00,0.00,0.0
1,1,Aruba,NaN,20200102,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.00,0.0,0.00,0.00,0.0
2,2,Aruba,NaN,20200103,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.00,0.0,0.00,0.00,0.0
3,3,Aruba,NaN,20200104,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.00,0.0,0.00,0.00,0.0
4,4,Aruba,NaN,20200105,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.00,0.0,0.00,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59040,59040,Zimbabwe,NaN,20200828,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,6292.0,189.0,80.56,88.1,66.03,73.48,25.0
59041,59041,Zimbabwe,NaN,20200829,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,6388.0,195.0,80.56,88.1,66.03,73.48,25.0
59042,59042,Zimbabwe,NaN,20200830,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,6406.0,196.0,80.56,88.1,66.03,73.48,25.0
59043,59043,Zimbabwe,NaN,20200831,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,6412.0,196.0,80.56,88.1,66.03,73.48,25.0
59044,59044,Zimbabwe,NaN,20200901,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,80.56,88.1,66.03,73.48,25.0

In [4]:
"""ox_date = ox[(ox['Date'] == 20200901)][['CountryName', 'ConfirmedCases', 'ConfirmedDeaths']]
ox_date.info()
No Info in September yet"""

ox_date = pd.pivot_table(ox, index='CountryName', values=['ConfirmedCases', 'ConfirmedDeaths'], aggfunc='max')
ox_date

             ConfirmedCases  ConfirmedDeaths
CountryName
Afghanistan         38162.0           1402.0
Albania              9380.0            280.0
Algeria             44146.0           1501.0
Andorra              1124.0             53.0
Angola               2624.0            107.0
...                     ...              ...
Venezuela           45868.0            381.0
Vietnam              1040.0             32.0
Yemen                1953.0            564.0
Zambia              12025.0            287.0
Zimbabwe             6412.0            196.0

[179 rows x 2 columns]

In [5]:
ox_date.columns
#CPF = Case Fatality Rate
ox_date['CPF'] = ox_date['ConfirmedDeaths']/ox_date['ConfirmedCases']*100
ox_date

#To calculate ratios, I need the population of each country which is in a different database

             ConfirmedCases  ConfirmedDeaths        CPF
CountryName
Afghanistan         38162.0           1402.0   3.673812
Albania              9380.0            280.0   2.985075
Algeria             44146.0           1501.0   3.400082
Andorra              1124.0             53.0   4.715302
Angola               2624.0            107.0   4.077744
...                     ...              ...        ...
Venezuela           45868.0            381.0   0.830644
Vietnam              1040.0             32.0   3.076923
Yemen                1953.0            564.0  28.878648
Zambia              12025.0            287.0   2.386694
Zimbabwe             6412.0            196.0   3.056769

[179 rows x 3 columns]

In [6]:
owid = pd.read_csv('C:\\Users\\sarah\\Documents\\IRONHACK\\Final_Project_Mod2\\owid-covid-data.csv')
owid.columns

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'new_tests', 'total_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'tests_per_case', 'positive_rate', 'tests_units', 'stringency_index',
       'population', 'population_density', 'median_age', 'aged_65_older',
       'aged_70_older', 'gdp_per_capita', 'extreme_poverty',
       'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers',
       'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy'],
      dtype='object')

In [7]:
owid_date = pd.pivot_table(owid, index='location', values=['total_cases', 'total_cases_per_million', 'total_deaths', 'total_deaths_per_million', 'population'], aggfunc='max')
owid_date
#Actually this table seems similar and even has world info.

,population,total_cases,total_cases_per_million,total_deaths,total_deaths_per_million
location,,,,,
Afghanistan,3.892834e+07,38196.0,981.187,1406.0,36.118
Albania,2.877800e+06,9513.0,3305.650,284.0,98.686
Algeria,4.385104e+07,44494.0,1014.662,1510.0,34.435
Andorra,7.726500e+04,1176.0,15220.346,53.0,685.951
Angola,3.286627e+07,2624.0,79.839,107.0,3.256
...,...,...,...,...,...
Western Sahara,5.973300e+05,766.0,1282.373,1.0,1.674
World,7.794799e+09,25509135.0,3272.584,850902.0,109.163
Yemen,2.982597e+07,1958.0,65.647,566.0,18.977
Zambia,1.838396e+07,12097.0,658.019,288.0,15.666
Zimbabwe,1.486293e+07,6497.0,437.128,202.0,13.591

In [8]:
owid_date['CPF'] = owid_date['total_deaths']/owid_date['total_cases']*100

owid_date['%Death'] = owid_date['total_deaths']/owid_date['population']*100

owid_date['%Cases'] = owid_date['total_cases']/owid_date['population']*100

owid_date

,population,total_cases,total_cases_per_million,total_deaths,total_deaths_per_million,CPF,%Death,%Cases
location,,,,,,,,
Afghanistan,3.892834e+07,38196.0,981.187,1406.0,36.118,3.681014,0.003612,0.098119
Albania,2.877800e+06,9513.0,3305.650,284.0,98.686,2.985388,0.009869,0.330565
Algeria,4.385104e+07,44494.0,1014.662,1510.0,34.435,3.393716,0.003443,0.101466
Andorra,7.726500e+04,1176.0,15220.346,53.0,685.951,4.506803,0.068595,1.522035
Angola,3.286627e+07,2624.0,79.839,107.0,3.256,4.077744,0.000326,0.007984
...,...,...,...,...,...,...,...,...
Western Sahara,5.973300e+05,766.0,1282.373,1.0,1.674,0.130548,0.000167,0.128237
World,7.794799e+09,25509135.0,3272.584,850902.0,109.163,3.335676,0.010916,0.327258
Yemen,2.982597e+07,1958.0,65.647,566.0,18.977,28.907048,0.001898,0.006565
Zambia,1.838396e+07,12097.0,658.019,288.0,15.666,2.380756,0.001567,0.065802
Zimbabwe,1.486293e+07,6497.0,437.128,202.0,13.591,3.109127,0.001359,0.043713

In [27]:
#owid_date.to_csv('C:\\Users\\sarah\\Documents\\IRONHACK\\Final_Project_Mod2\\data\\covid_cpf_per_country.csv')

In [9]:
owid_time = owid[['location', 'date', 'new_cases_per_million', 'total_cases_per_million', 'new_deaths_per_million', 'total_deaths_per_million']]

In [10]:
owid_time.sample(20)

,location,date,new_cases_per_million,total_cases_per_million,new_deaths_per_million,total_deaths_per_million
40448,Zimbabwe,14/08/2020,6.526,335.735,0.404,8.612
20878,Latvia,01/04/2020,11.664,211.006,0.000,0.000
31988,Senegal,24/03/2020,0.717,4.718,0.000,0.000
722,Andorra,30/04/2020,0.000,9616.256,12.942,543.584
14637,Gibraltar,30/05/2020,118.726,4778.724,0.000,0.000
31376,Saint Vincent and the Grenadines,15/08/2020,0.000,513.759,0.000,0.000
3211,Bangladesh,17/06/2020,23.450,573.692,0.322,7.663
21791,Liechtenstein,22/05/2020,0.000,2176.364,0.000,26.221
16056,Guinea-Bissau,09/06/2020,10.671,705.793,0.000,6.098
9247,Cuba,11/05/2020,1.059,155.916,0.265,6.798
37256,Tunisia,26/05/2020,0.000,88.927,0.000,4.061
35917,Taiwan,13/02/2020,0.000,0.756,0.000,0.000
14351,Germany,21/07/2020,6.230,2415.081,0.048,108.493
23589,Malta,04/04/2020,31.707,514.111,0.000,0.000
32989,Sint Maarten (Dutch part),26/05/2020,0.000,1795.625,0.000,349.797
36404,Tanzania,25/08/2020,0.000,8.521,0.000,0.352
38597,United States,16/03/2020,2.486,11.402,0.036,0.208
19053,Jamaica,22/05/2020,1.689,180.335,0.000,3.039
18999,Jamaica,29/03/2020,2.026,10.807,0.000,0.338
19634,Jordan,12/05/2020,2.156,55.081,0.000,0.882

In [11]:
owid_time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40959 entries, 0 to 40958
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   location                  40959 non-null  object
 1   date                      40959 non-null  object
 2   new_cases_per_million     40138 non-null  float64
 3   total_cases_per_million   40138 non-null  float64
 4   new_deaths_per_million    40138 non-null  float64
 5   total_deaths_per_million  40138 non-null  float64
dtypes: float64(4), object(2)
memory usage: 1.9+ MB

In [23]:
#owid_time.to_csv('C:\\Users\\sarah\\Documents\\IRONHACK\\Final_Project_Mod2\\data\\covid_vs_time.csv')

,Unnamed: 0,CountryName,RegionName,Date,C1_School closing,C2_Workplace closing,C3_Cancel public events,C4_Restrictions on gatherings,C5_Close public transport,C6_Stay at home requirements,...,H3_Contact tracing,H4_Emergency investment in healthcare,H5_Investment in vaccines,ConfirmedCases,ConfirmedDeaths,StringencyIndexForDisplay,StringencyLegacyIndexForDisplay,GovernmentResponseIndexForDisplay,ContainmentHealthIndexForDisplay,EconomicSupportIndexForDisplay
0,0,Aruba,NaN,20200101,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
1,1,Aruba,NaN,20200102,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
2,2,Aruba,NaN,20200103,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
3,3,Aruba,NaN,20200104,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
4,4,Aruba,NaN,20200105,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
5,5,Aruba,NaN,20200106,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
6,6,Aruba,NaN,20200107,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
7,7,Aruba,NaN,20200108,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
8,8,Aruba,NaN,20200109,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
9,9,Aruba,NaN,20200110,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
10,10,Aruba,NaN,20200111,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
11,11,Aruba,NaN,20200112,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
12,12,Aruba,NaN,20200113,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
13,13,Aruba,NaN,20200114,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
14,14,Aruba,NaN,20200115,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
15,15,Aruba,NaN,20200116,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
16,16,Aruba,NaN,20200117,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
17,17,Aruba,NaN,20200118,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
18,18,Aruba,NaN,20200119,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
19,19,Aruba,NaN,20200120,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
20,20,Aruba,NaN,20200121,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
21,21,Aruba,NaN,20200122,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
22,22,Aruba,NaN,20200123,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
23,23,Aruba,NaN,20200124,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
24,24,Aruba,NaN,20200125,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
25,25,Aruba,NaN,20200126,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
26,26,Aruba,NaN,20200127,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
27,27,Aruba,NaN,20200128,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
28,28,Aruba,NaN,20200129,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
29,29,Aruba,NaN,20200130,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
30,30,Aruba,NaN,20200131,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
31,31,Aruba,NaN,20200201,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
32,32,Aruba,NaN,20200202,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
33,33,Aruba,NaN,20200203,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
34,34,Aruba,NaN,20200204,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
35,35,Aruba,NaN,20200205,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
36,36,Aruba,NaN,20200206,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
37,37,Aruba,NaN,20200207,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
38,38,Aruba,NaN,20200208,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
39,39,Aruba,NaN,20200209,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
40,40,Aruba,NaN,20200210,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
41,41,Aruba,NaN,20200211,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
42,42,Aruba,NaN,20200212,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
43,43,Aruba,NaN,20200213,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
44,44,Aruba,NaN,20200214,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
45,45,Aruba,NaN,20200215,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
46,46,Aruba,NaN,20200216,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
47,47,Aruba,NaN,20200217,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
48,48,Aruba,NaN,20200218,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
49,49,Aruba,NaN,20200219,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
50,50,Aruba,NaN,20200220,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
51,51,Aruba,NaN,20200221,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
52,52,Aruba,NaN,20200222,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
53,53,Aruba,NaN,20200223,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
54,54,Aruba,NaN,20200224,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
55,55,Aruba,NaN,20200225,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
56,56,Aruba,NaN,20200226,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
57,57,Aruba,NaN,20200227,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
58,58,Aruba,NaN,20200228,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
59,59,Aruba,NaN,20200229,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0